/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemporadaRouteImport } from './routes/temporada'
import { Route as SerieRouteImport } from './routes/serie'
import { Route as PessoaRouteImport } from './routes/pessoa'
import { Route as EpisodioRouteImport } from './routes/episodio'
import { Route as DirecoesRouteImport } from './routes/direcoes'
import { Route as DetalheRouteImport } from './routes/detalhe'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const TemporadaRoute = TemporadaRouteImport.update({
  id: '/temporada',
  path: '/temporada',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieRoute = SerieRouteImport.update({
  id: '/serie',
  path: '/serie',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoaRoute = PessoaRouteImport.update({
  id: '/pessoa',
  path: '/pessoa',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodioRoute = EpisodioRouteImport.update({
  id: '/episodio',
  path: '/episodio',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecoesRoute = DirecoesRouteImport.update({
  id: '/direcoes',
  path: '/direcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DetalheRoute = DetalheRouteImport.update({
  id: '/detalhe',
  path: '/detalhe',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/detalhe': typeof DetalheRoute
  '/direcoes': typeof DirecoesRoute
  '/episodio': typeof EpisodioRoute
  '/pessoa': typeof PessoaRoute
  '/serie': typeof SerieRoute
  '/temporada': typeof TemporadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/detalhe': typeof DetalheRoute
  '/direcoes': typeof DirecoesRoute
  '/episodio': typeof EpisodioRoute
  '/pessoa': typeof PessoaRoute
  '/serie': typeof SerieRoute
  '/temporada': typeof TemporadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/detalhe': typeof DetalheRoute
  '/direcoes': typeof DirecoesRoute
  '/episodio': typeof EpisodioRoute
  '/pessoa': typeof PessoaRoute
  '/serie': typeof SerieRoute
  '/temporada': typeof TemporadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/detalhe'
    | '/direcoes'
    | '/episodio'
    | '/pessoa'
    | '/serie'
    | '/temporada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/detalhe'
    | '/direcoes'
    | '/episodio'
    | '/pessoa'
    | '/serie'
    | '/temporada'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/detalhe'
    | '/direcoes'
    | '/episodio'
    | '/pessoa'
    | '/serie'
    | '/temporada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DetalheRoute: typeof DetalheRoute
  DirecoesRoute: typeof DirecoesRoute
  EpisodioRoute: typeof EpisodioRoute
  PessoaRoute: typeof PessoaRoute
  SerieRoute: typeof SerieRoute
  TemporadaRoute: typeof TemporadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temporada': {
      id: '/temporada'
      path: '/temporada'
      fullPath: '/temporada'
      preLoaderRoute: typeof TemporadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie': {
      id: '/serie'
      path: '/serie'
      fullPath: '/serie'
      preLoaderRoute: typeof SerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoa': {
      id: '/pessoa'
      path: '/pessoa'
      fullPath: '/pessoa'
      preLoaderRoute: typeof PessoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodio': {
      id: '/episodio'
      path: '/episodio'
      fullPath: '/episodio'
      preLoaderRoute: typeof EpisodioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcoes': {
      id: '/direcoes'
      path: '/direcoes'
      fullPath: '/direcoes'
      preLoaderRoute: typeof DirecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detalhe': {
      id: '/detalhe'
      path: '/detalhe'
      fullPath: '/detalhe'
      preLoaderRoute: typeof DetalheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  DetalheRoute: DetalheRoute,
  DirecoesRoute: DirecoesRoute,
  EpisodioRoute: EpisodioRoute,
  PessoaRoute: PessoaRoute,
  SerieRoute: SerieRoute,
  TemporadaRoute: TemporadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
